### ISSUE TITLE
Is there a way to calibrate the readings?

### ISSUE THREAD

**Issue by kandev** [uvjim/rpi_waveshare_ups#7]
Hello and thank you for the wonderful work! That's the only usable "plugin" for HASS OS.

Is there a convenient way to calibrate the readings and the battery capacity? My issue is that it shows 90% at full charge and around 40% before shutdown.

**Comment by uvjim** [comment]
Sorry, I missed this one.

No, there isn't currently a way to adjust the readings in the integration. It was implemented using the example code from waveshare which didn't accommodate that.
